name: deploy_frontend_openid

on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name azresumewebpagestg --auth-mode key -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "sanelresume" --name "sanelresume" --resource-group "resumewebpage-rg"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()